// This file is automatically generated. Edits are allowed to add env fallbacks and safer storage handling.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Prefer Vite env variables so keys can be injected per-environment.
// Vite exposes env vars prefixed with VITE_ at build time via import.meta.env
const SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL as string) || "https://yybkllzjftowdnqhzdbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = (import.meta.env.VITE_SUPABASE_ANON_KEY as string) || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5YmtsbHpqZnRvd2RucWh6ZGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzA0MTUsImV4cCI6MjA3MzEwNjQxNX0.v47mlfWeaNZUyfAZLXoma86NfcUUCal1PsO9FZ-OQtU";

// Storage may not be available in some runtimes (SSR/test). Only pass localStorage if available.
const storage = typeof window !== 'undefined' && typeof window.localStorage !== 'undefined'
  ? (window.localStorage as unknown as Storage)
  : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage,
    persistSession: true,
    autoRefreshToken: true,
  }
});