// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yybkllzjftowdnqhzdbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5YmtsbHpqZnRvd2RucWh6ZGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzA0MTUsImV4cCI6MjA3MzEwNjQxNX0.v47mlfWeaNZUyfAZLXoma86NfcUUCal1PsO9FZ-OQtU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});